version: "3"

services:
  ooni-probe:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "ooni-probe"
    restart: unless-stopped
    # Overrides the default command and runs the probe at random times
    command: >
      sh -c "/usr/bin/ooniprobe run unattended --batch
      && /bin/sleep sleep $(shuf -i 3600-4200 -n 1)"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 100m
